### PR TITLE
Add VPC Peering capability for each created private subnet within VPC

### PR DESCRIPTION
**Pull request by aczajkowski**
This change allows to add vpc peering connections to created VPC be providing their id's
e.g.
``` 
terraformResources:
        - type: vpc
          variables:
            vpc_name: "${clusterRequest.clusterId}-vpc"
            vpc_cidr: "10.5.0.0/24"
            public_subnet_list:
              - us-west-2a
              - us-west-2b
            private_subnet_list:
              - us-west-2a
              - us-west-2b
            private_subnet_pcx_vpc_ids_list :
              - <<vpc_id_0>>
              - <<vpc_id_1>>
```

### CODE REVIEW

**Comment by jvanzyl** [comment]
So this needs to work for the peering and non-peering use cases? How are you doing that here? @ajayk is it possibly to layer in peering after a VPC is made?

**Comment by aczajkowski** [comment]
@jvanzyl 
> So this needs to work for the peering and non-peering use cases? How are you doing that here? @ajayk is it possibly to layer in peering after a VPC is made?

Peering is optional here https://github.com/concord-workflow/concord-terraform/blob/1b227d5b74228f8871e323d71abe2ee6320e88a9/0.12/aws/vpc/vpc-peer.tf#L2

So once this variable is not defined there will be no Peering connections created.

**Comment by jvanzyl** [comment]
Maybe something like:

```
private_subnets_to_peer:
  - vpc_id0
  - vpc_id1
```

The `public_subnet_list` is a holdover from when we converted from a map to a list and need both forms in there but that can probably be `public_subnets` but we can change that later.

**Comment by aczajkowski** [comment]
@jvanzyl @ajayk - I've modified variable name to "private_subnet_pcx_vpcs"
and updated commit in PR.

**Pull request merged**
